### ISSUE TITLE
Down?

### ISSUE THREAD

**Issue by ManuelSchneid3r** [Brawl345/tagesschau-eilbot#1]
Haufenweise nachrichten werden ausgelassen. deit drei tagen geht gar nichts mehr.

**Comment by Brawl345** [comment]
Die letzte Eilmeldung bei mir ist "Bundesverfassungsgericht kippt Berliner Mietendeckel", danach kam nur noch "DTrend im ARD-Morgenmagazin: Söder bei K-Frage deutlich vor Laschet", was aber nicht als Eilmeldung ausgewiesen wurde von der API. Danach kamen keine neuen Eilmeldungen mehr (vgl. https://twitter.com/tagesschau_eil ).

**Comment by Brawl345** [comment]
Mit der letzten Eilmeldung erübrigt sich das ja, funktioniert wie es soll. Vielleicht nochmal re-subscriben mit /start falls nichts mehr kommt.
